### ISSUE TITLE
Functions have no headers!

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [RedBelette/RED_FRAMEWORK#39]
suggested header template:
/*
*Function name/ Nom de la fonction:
*Author/ Auteur:
*
*EN:
*Usage:
* Example:
*
*FR:
*Utilisation:
*Exemple:
*/

**Comment by RedBelette** [comment]
It's a good suggestion, we can apply it!

**Comment by RedBelette** [comment]
I have included this issue inside this sprint.

**Comment by RedBelette** [comment]
More informations
/*
* Function name / Nom de la fonction: 
* Author / Auteur: RedBelette
* Since version/ Depuis la version: 1.0.0
* Doc URL: http://www.redframework.com/project-detail/core
*
* EN:
* Usage:
* Example:
*
* FR:
* Utilisation: 
* Exemple:
*/

**Comment by RedBelette** [comment]
@DEPRECATED to specify that the function is deprecated and may be deleted on next medior version.
