### ISSUE TITLE
functions that need renaming in proper English: ;-)

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [RedBelette/RED_FRAMEWORK#40]
Maybe:
Rename 
fn_loadingFinished ==> fn_loadingComplete
fn_makeAllUnitsEditableForAllCurator ==> fn_makeAllUnitsEditableForAllCurators
fn_makeObjectsEditableForAllCurator ==> fn_makeObjectsEditableForAllCurators

Necessary:
Rename
fn_initHelico ==> fn_heliInit
fn_landingHelico ==> fn_landHeli
fn_reddition ==> fn_MakeSideSurrender (or maybe fn_SideSurrenderThreshold ?)
fn_sendHelicoToFight ==> fn_sendHeliToFight (maybe fn_HeliToCombatZone ?)
fn_spawnGranisons ==> fn_spawnGarrison

**Comment by RedBelette** [comment]
Both lists can be changed. By convention i start the name of a function a lower capital letter. fn_MakeSideSurrender -> fn_makeSideSurrender. 

I prefer fn_makeSideSurrender and fn_sendHeliToFight.

**Comment by RedBelette** [comment]
What's your opinion about fn_HeliToCombatZone ?

**Comment by RedBelette** [comment]
I have included this issue inside this sprint.
